# Generated by Django 4.1.1 on 2022-10-05 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assinatura', models.CharField(max_length=250)),
                ('pub_date', models.DateTimeField(verbose_name='data de publicacao')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
