# Generated by Django 4.1.1 on 2022-10-05 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='texto',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to='img'),
        ),
    ]
