# Generated by Django 4.1.1 on 2022-10-05 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('omage', '0002_card_texto_alter_card_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
